### PR TITLE
Revert "Fixing some printf errors in latest dev compilation"

### PR DESCRIPTION
**Pull request by gabest11**
Reverts gabest11/esphome#1

### CODE REVIEW

**Comment by fightforlife** [comment]
@gabest11 : My compiler is still complaining about the missing "l".
I think the bots are not up to date.

```
src/esphome/components/cc1101/cc1101.cpp: In member function 'virtual void esphome::cc1101::CC1101::dump_config()':
src/esphome/components/cc1101/cc1101.cpp:209:22: error: format '%u' expects argument of type 'unsigned int', but argument 5 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  209 |   ESP_LOGCONFIG(TAG, "  CC1101 Bandwith: %u KHz", this->bandwidth_);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
   72 | #define ESPHOME_LOG_FORMAT(format) format
      |                                    ^~~~~~
src/esphome/core/log.h:153:33: note: in expansion of macro 'esph_log_config'
  153 | #define ESP_LOGCONFIG(tag, ...) esph_log_config(tag, __VA_ARGS__)
      |                                 ^~~~~~~~~~~~~~~
src/esphome/components/cc1101/cc1101.cpp:209:3: note: in expansion of macro 'ESP_LOGCONFIG'
  209 |   ESP_LOGCONFIG(TAG, "  CC1101 Bandwith: %u KHz", this->bandwidth_);
      |   ^~~~~~~~~~~~~
src/esphome/components/cc1101/cc1101.cpp:209:43: note: format string is defined here
  209 |   ESP_LOGCONFIG(TAG, "  CC1101 Bandwith: %u KHz", this->bandwidth_);
      |                                          ~^
      |                                           |
      |                                           unsigned int
      |                                          %lu
```

If I include the l for int32/uint32 values, it compiles just fine.

**Comment by gabest11** [comment]
What are you using? I update my docker image and no problems.

**Comment by gabest11** [comment]
Maybe we should go full retard and use %PRIu32

**Comment by fightforlife** [comment]
I just pulled the latest esphome dev container. I am using esp32 with IDF 5.2.1. If I include the esphome PR6300 with refresh 0s I still get these errors.
I am not sure what %PRlu32 does, but I can try tomorrow.

**Comment by gabest11** [comment]
It's from what you linked last time: [That's the format specifier for uint32_t](https://github.com/espressif/esp-idf/issues/6906#issuecomment-2067741057)

I don't know how our compilers can be different. I updated to the last working image 2024.4.2 and checked out each commit one-by-one until I hit the one with the memory problems, then updated to HEAD, still worked. 

It could be a recent change in the image.

**Comment by gabest11** [comment]
I have just tried 2024.6.0-dev20240528. Appart from a small breaking change in the ota component, it compiled without errors. 

Ah, I can't read, you wrote idf, and I am testing arduino (8266 only has that).

**Comment by gabest11** [comment]
What a pain, it does complain about it, and a few other remote modules are also broken. I will just rewrite everything to the good old regular "int".

**Pull request merged**
